name: Docker build push pipeline

on: push

env:
  VERSION: 1.0
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
    
    - name: Build docker image
      run: "docker build https://github.com/naman-26/DevOps_practice.git#main:. -t ${{ secrets.USERNAME }}/${{ vars.REPO_NAME }}:${{env.VERSION}}"
      
    - name: Push docker image
      run: "docker push ${{ secrets.USERNAME }}/${{ vars.REPO_NAME }}:${{env.VERSION}}"
